name:           "Matt Cocci"
description:    ""

url:            http://localhost:9001

permalinks:     pretty
pygments:       true

port:           9001
baseurl:        /
encoding:       UTF-8
layout:         default
markdown:       kramdown

# My sites
myPages: 
  Twitter:    <a href="http://twitter.com/MattCocci" target="_blank">Twitter</a>
  Github:     <a href="http://github.com/MattCocci" target="_blank">Github</a>
  Notes:      <a href="http://github.com/MattCocci/Notes" target="_blank">Notes</a>
  Goodreads:  <a href="https://www.goodreads.com/user/show/18990627-matthew-cocci" target="_blank">Goodreads</a>
  LinkedIn:   <a href="http://lnkd.in/_RKJCM" target="_blank">LinkedIn</a>
  Email:      <a href="mailto:matthew.cocci@gmail.com" target="_blank">Email</a>
