name:           "Matt Cocci"
description:    ""

url:            http://localhost:9001

permalinks:     pretty
pygments:       true

port:           9001
baseurl:        /
encoding:       UTF-8
layout:         default
markdown:       kramdown

# My sites
Twitter:    "http://twitter.com/MattCocci"
Github:     "http://github.com/MattCocci"
Notes:      "http://github.com/MattCocci/Notes"
Goodreads:  "https://www.goodreads.com/user/show/18990627-matthew-cocci"
